version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: task_manager_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/task_manager
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
